DROP DATABASE IF EXISTS contactDB;
CREATE DATABASE contactDB;

USE contactDB;

CREATE TABLE Contact(
ContactId INT PRIMARY KEY AUTO_INCREMENT,

FirstName VARCHAR(20) NOT NULL,
LastName VARCHAR(20) NOT NULL,
Email VARCHAR(30) NOT NULL,
Phone CHAR(14) NOT NULL
);

CREATE TABLE Agent(
AgentId INT PRIMARY KEY AUTO_INCREMENT,

`Name` VARCHAR(20) NOT NULL,
`Password` VARCHAR(20) NOT NULL
);

CREATE TABLE Log(
LogId INT PRIMARY KEY AUTO_INCREMENT,

ContactId INT NOT NULL,
`Timestamp` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
LogMessage VARCHAR(255) DEFAULT '',
AgentId INT NOT NULL,

FOREIGN KEY fk_Log_ContactId (ContactId)
    REFERENCES Contact(ContactId),
FOREIGN KEY fk_Agent_AgentId (AgentId)
    REFERENCES Agent(AgentId)
);

